//! Phase 2A.1 — CR 613 Layered Effects Engine
//!
//! Magic: The Gathering uses a layered system (CR 613) to determine the
//! characteristics of objects on the battlefield when multiple continuous
//! effects interact. Effects are applied in a strict layer order:
//!
//! - Layer 1: Copy effects
//! - Layer 2: Control-changing effects
//! - Layer 3: Text-changing effects
//! - Layer 4: Type-changing effects
//! - Layer 5: Color-changing effects
//! - Layer 6: Ability-adding/removing effects
//! - Layer 7: Power/toughness modifications (sublayers a-e)
//!
//! Within each layer, effects are applied in timestamp order (CR 613.7).
//! The layer engine recomputes characteristics from scratch each time,
//! ensuring determinism regardless of the order effects were created.
//!
//! # Performance
//!
//! The engine is designed for use in MCCFR traversal where millions of
//! `GameState::clone()` calls happen. Continuous effects are stored as
//! data on `GameState` (cheaply cloneable) and characteristics are
//! recomputed on demand rather than cached.

use serde::{Deserialize, Serialize};

use crate::card::{CardId, CardType, KeywordAbility, ObjectId, Subtype};
use crate::game::PlayerIndex;
use crate::mana::Color;

/// A continuous effect active on the battlefield, generated by a static
/// ability, resolved spell, or other game action.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ContinuousEffect {
    /// The permanent or effect that generates this continuous effect.
    pub source_id: ObjectId,
    /// The player who controls the source.
    pub controller: PlayerIndex,
    /// Timestamp for ordering within the same layer (CR 613.7).
    /// Lower timestamps are applied first.
    pub timestamp: u32,
    /// How long this effect lasts.
    pub duration: Duration,
    /// What objects this effect applies to.
    pub affected: AffectedObjects,
    /// What modification this effect makes. Each ContinuousEffect
    /// applies exactly one modification in one layer.
    pub modification: LayerModification,
}

/// How long a continuous effect lasts.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Duration {
    /// Lasts as long as the source permanent is on the battlefield.
    /// Used by static abilities (e.g., Glorious Anthem).
    WhileSourceOnBattlefield,
    /// Lasts until end of turn (cleaned up in cleanup step).
    UntilEndOfTurn,
    /// Permanent modification (e.g., from a resolved spell like Riding the Dilu Horse).
    Permanent,
    /// Lasts as long as the source card is in a graveyard (e.g., Wonder).
    WhileSourceInGraveyard,
}

/// What objects a continuous effect applies to.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AffectedObjects {
    /// Only the source permanent itself.
    Source,
    /// A specific object by ID.
    Specific(ObjectId),
    /// All creatures on the battlefield.
    AllCreatures,
    /// All creatures controlled by a specific player.
    CreaturesControlledBy(PlayerIndex),
    /// All creatures except the source.
    OtherCreatures,
    /// All creatures controlled by a specific player except the source.
    OtherCreaturesControlledBy(PlayerIndex),
    /// All non-Human creatures controlled by a specific player except the source
    /// (e.g., Mikaeus, the Unhallowed: "Other non-Human creatures you control").
    OtherNonHumanCreaturesControlledBy(PlayerIndex),
    /// All permanents on the battlefield.
    AllPermanents,
    /// All permanents controlled by a specific player.
    PermanentsControlledBy(PlayerIndex),
    /// Other creatures with a specific subtype controlled by a player
    /// (e.g., Ashcoat: "other Rats you control").
    OtherCreaturesWithSubtypeControlledBy(String, PlayerIndex),
    /// The permanent this source is attached to (equipment/aura buffs).
    AttachedTo,
    /// Other creatures of a subtype controlled by the source's current controller.
    OtherCreaturesWithSubtypeControlledBySource(String),
}

/// A single modification applied by a continuous effect, keyed to its layer.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum LayerModification {
    // --- Layer 1: Copy effects ---
    /// Become a copy of another card definition.
    CopyOf(CardId),

    // --- Layer 2: Control-changing effects ---
    /// Change the controller of the affected object.
    ChangeController(PlayerIndex),

    // --- Layer 3: Text-changing effects ---
    // Not commonly needed for the current card pool; placeholder.

    // --- Layer 4: Type-changing effects ---
    /// Add a card type.
    AddType(CardType),
    /// Remove a card type.
    RemoveType(CardType),
    /// Set card types to exactly these (overwrite).
    SetTypes(Vec<CardType>),
    /// Add a subtype.
    AddSubtype(Subtype),

    // --- Layer 5: Color-changing effects ---
    /// Add a color.
    AddColor(Color),
    /// Set colors to exactly these (overwrite).
    SetColors(Vec<Color>),

    // --- Layer 6: Ability-adding/removing effects ---
    /// Grant a keyword ability.
    AddKeyword(KeywordAbility),
    /// Remove a specific keyword ability.
    RemoveKeyword(KeywordAbility),
    /// Remove all abilities (e.g., Humility).
    RemoveAllAbilities,

    // --- Layer 7a: Characteristic-defining abilities for P/T ---
    /// Set base power and toughness from a CDA (e.g., Tarmogoyf).
    SetBasePT(i32, i32),

    // --- Layer 7b: Effects that set P/T to specific values ---
    /// Set P/T to specific values (e.g., Humility sets to 1/1).
    SetPT(i32, i32),

    // --- Layer 7c: Effects that modify P/T (add/subtract) ---
    /// Modify P/T by delta (e.g., +1/+1 from Glorious Anthem).
    ModifyPT(i32, i32),

    // --- Layer 7d: Counters ---
    // Counters are handled directly from CardInstance.plus_counters/minus_counters
    // and are applied in layer 7d automatically by compute_characteristics().

    // --- Layer 7e: P/T switching ---
    /// Switch power and toughness.
    SwitchPT,
}

impl LayerModification {
    /// Which layer does this modification belong to?
    pub fn layer(&self) -> Layer {
        match self {
            LayerModification::CopyOf(_) => Layer::L1Copy,
            LayerModification::ChangeController(_) => Layer::L2Control,
            LayerModification::AddType(_)
            | LayerModification::RemoveType(_)
            | LayerModification::SetTypes(_)
            | LayerModification::AddSubtype(_) => Layer::L4Type,
            LayerModification::AddColor(_) | LayerModification::SetColors(_) => Layer::L5Color,
            LayerModification::AddKeyword(_)
            | LayerModification::RemoveKeyword(_)
            | LayerModification::RemoveAllAbilities => Layer::L6Ability,
            LayerModification::SetBasePT(_, _) => Layer::L7a,
            LayerModification::SetPT(_, _) => Layer::L7b,
            LayerModification::ModifyPT(_, _) => Layer::L7c,
            LayerModification::SwitchPT => Layer::L7e,
        }
    }
}

/// The layers defined by CR 613, in application order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Layer {
    L1Copy,
    L2Control,
    L3Text,
    L4Type,
    L5Color,
    L6Ability,
    L7a, // Characteristic-defining abilities
    L7b, // P/T-setting effects
    L7c, // P/T-modifying effects (+N/+N)
    L7d, // Counters (handled implicitly)
    L7e, // P/T switching
}

/// The computed characteristics of an object after applying all
/// continuous effects through the layer system.
#[derive(Debug, Clone)]
pub struct ComputedCharacteristics {
    pub card_types: Vec<CardType>,
    pub subtypes: Vec<Subtype>,
    pub colors: Vec<Color>,
    pub keywords: Vec<KeywordAbility>,
    pub power: i32,
    pub toughness: i32,
    /// The controller (may differ from base if Layer 2 effects apply).
    pub controller: PlayerIndex,
    /// Whether all abilities were removed (e.g., by Humility).
    pub abilities_removed: bool,
}

/// Compute the characteristics of a specific object after applying
/// all active continuous effects through the CR 613 layer system.
///
/// This function is the single source of truth for "what are this
/// object's characteristics right now?" It replaces the old
/// `effective_power()`, `effective_toughness()`, and `has_keyword()`
/// methods with a unified layer-based computation.
///
/// # Arguments
///
/// * `obj_id` - The object to compute characteristics for
/// * `effects` - All active continuous effects on the battlefield
/// * `objects` - All card instances (for reading base stats)
/// * `card_db` - Card definitions database
/// * `dyn_ctx` - Optional context for evaluating DynamicValue (hand/graveyard data)
pub fn compute_characteristics(
    obj_id: ObjectId,
    effects: &[ContinuousEffect],
    objects: &std::collections::HashMap<ObjectId, crate::card::CardInstance>,
    battlefield: &std::collections::HashSet<ObjectId>,
    card_db: &crate::game::CardDatabase,
) -> Option<ComputedCharacteristics> {
    compute_characteristics_with_ctx(obj_id, effects, objects, battlefield, card_db, None)
}

/// Like `compute_characteristics` but accepts an optional `DynamicContext`
/// for evaluating `DynamicValue::CardsInHand` and `CardTypesInGraveyards`.
pub fn compute_characteristics_with_ctx(
    obj_id: ObjectId,
    effects: &[ContinuousEffect],
    objects: &std::collections::HashMap<ObjectId, crate::card::CardInstance>,
    battlefield: &std::collections::HashSet<ObjectId>,
    card_db: &crate::game::CardDatabase,
    dyn_ctx: Option<&crate::card::DynamicContext>,
) -> Option<ComputedCharacteristics> {
    compute_characteristics_through_layer(
        obj_id, effects, objects, battlefield, card_db, dyn_ctx, None,
    )
}

/// A bounded layer pass lets later filters read the source's Layer 2 controller
/// without recursively evaluating that source's anthems.
fn compute_characteristics_through_layer(
    obj_id: ObjectId,
    effects: &[ContinuousEffect],
    objects: &std::collections::HashMap<ObjectId, crate::card::CardInstance>,
    battlefield: &std::collections::HashSet<ObjectId>,
    card_db: &crate::game::CardDatabase,
    dyn_ctx: Option<&crate::card::DynamicContext>,
    through: Option<Layer>,
) -> Option<ComputedCharacteristics> {
    let inst = objects.get(&obj_id)?;
    let def = card_db.get(inst.card_def_id)?;

    // Start from base characteristics (the printed card)
    let mut card_types = def.card_types.clone();
    let mut subtypes = def.subtypes.clone();
    let mut colors = def.base_colors();
    let mut keywords = def.keywords.clone();
    let mut power = def.power.unwrap_or(0);
    let mut toughness = def.toughness.unwrap_or(0);
    let mut controller = inst.controller;
    let mut abilities_removed = false;
    let mut counters_applied = false;

    // Layer 7a: Evaluate dynamic power/toughness (CDA) if present.
    // These characteristic-defining abilities set the base P/T from game state.
    if def.dynamic_power.is_some() || def.dynamic_toughness.is_some() {
        let bf_vec: Vec<ObjectId> = battlefield.iter().copied().collect();
        if let Some(ref dyn_pow) = def.dynamic_power {
            power = dyn_pow.evaluate(controller, objects, &bf_vec, &|id| card_db.get(id), dyn_ctx);
        }
        if let Some(ref dyn_tough) = def.dynamic_toughness {
            toughness = dyn_tough.evaluate(controller, objects, &bf_vec, &|id| card_db.get(id), dyn_ctx);
        }
    }

    // Collect effects that apply to this object, sorted by (layer, timestamp)
    let mut applicable: Vec<&ContinuousEffect> = effects
        .iter()
        .filter(|e| through.map_or(true, |layer| e.modification.layer() <= layer))
        .filter(|e| effect_applies_to(e, obj_id, inst, objects, battlefield, card_db))
        .collect();

    applicable.sort_by(|a, b| {
        let la = a.modification.layer();
        let lb = b.modification.layer();
        la.cmp(&lb).then(a.timestamp.cmp(&b.timestamp))
    });

    // Apply effects in layer order
    for effect in &applicable {
        if let AffectedObjects::OtherCreaturesWithSubtypeControlledBySource(subtype) = &effect.affected {
            let source_controller = compute_characteristics_through_layer(
                effect.source_id, effects, objects, battlefield, card_db, None,
                Some(Layer::L2Control),
            ).map(|c| c.controller);
            if source_controller != Some(controller)
                || !card_types.contains(&CardType::Creature)
                || !(subtypes.iter().any(|s| s.0 == *subtype)
                    || keywords.contains(&KeywordAbility::Changeling)
                    || inst.temp_keywords.contains(&KeywordAbility::Changeling))
            {
                continue;
            }
        }
        match &effect.modification {
            // --- Layer 1: Copy ---
            LayerModification::CopyOf(copy_id) => {
                if let Some(copy_def) = card_db.get(*copy_id) {
                    card_types = copy_def.card_types.clone();
                    subtypes = copy_def.subtypes.clone();
                    colors = copy_def.base_colors();
                    keywords = copy_def.keywords.clone();
                    power = copy_def.power.unwrap_or(0);
                    toughness = copy_def.toughness.unwrap_or(0);
                }
            }

            // --- Layer 2: Control ---
            LayerModification::ChangeController(new_controller) => {
                controller = *new_controller;
            }

            // --- Layer 4: Type ---
            LayerModification::AddType(t) => {
                if !card_types.contains(t) {
                    card_types.push(*t);
                }
            }
            LayerModification::RemoveType(t) => {
                card_types.retain(|ct| ct != t);
            }
            LayerModification::SetTypes(types) => {
                card_types = types.clone();
            }
            LayerModification::AddSubtype(st) => {
                if !subtypes.contains(st) {
                    subtypes.push(st.clone());
                }
            }

            // --- Layer 5: Color ---
            LayerModification::AddColor(c) => {
                if !colors.contains(c) {
                    colors.push(*c);
                }
            }
            LayerModification::SetColors(c) => {
                colors = c.clone();
            }

            // --- Layer 6: Ability ---
            LayerModification::AddKeyword(kw) => {
                // Grants apply regardless of whether abilities were removed
                // (a later-timestamp grant overrides an earlier RemoveAllAbilities)
                if !keywords.contains(kw) {
                    keywords.push(*kw);
                }
            }
            LayerModification::RemoveKeyword(kw) => {
                keywords.retain(|k| k != kw);
            }
            LayerModification::RemoveAllAbilities => {
                keywords.clear();
                abilities_removed = true;
            }

            // --- Layer 7a: CDA for P/T ---
            LayerModification::SetBasePT(p, t) => {
                power = *p;
                toughness = *t;
            }

            // --- Layer 7b: Set P/T ---
            LayerModification::SetPT(p, t) => {
                power = *p;
                toughness = *t;
            }

            // --- Layer 7c: Modify P/T ---
            LayerModification::ModifyPT(dp, dt) => {
                power += dp;
                toughness += dt;
            }

            // --- Layer 7e: Switch P/T ---
            // Layer 7d (counters) is applied just before we reach 7e effects.
            LayerModification::SwitchPT => {
                if !counters_applied {
                    power += inst.plus_counters - inst.minus_counters;
                    toughness += inst.plus_counters - inst.minus_counters;
                    counters_applied = true;
                }
                std::mem::swap(&mut power, &mut toughness);
            }
        }
    }

    // Layer 7d: Apply counters if not already applied (no SwitchPT was present)
    if !counters_applied {
        power += inst.plus_counters - inst.minus_counters;
        toughness += inst.plus_counters - inst.minus_counters;
    }

    // Apply temporary keywords from CardInstance (set by resolve_effect).
    // These represent EoT effects that haven't been converted to continuous effects.
    for kw in &inst.temp_keywords {
        if !keywords.contains(kw) {
            keywords.push(*kw);
        }
    }

    // Apply temporary power/toughness modifications from CardInstance.
    power += inst.temp_power_mod;
    toughness += inst.temp_toughness_mod;

    Some(ComputedCharacteristics {
        card_types,
        subtypes,
        colors,
        keywords,
        power,
        toughness,
        controller,
        abilities_removed,
    })
}

/// Check if a continuous effect applies to a specific object.
fn effect_applies_to(
    effect: &ContinuousEffect,
    obj_id: ObjectId,
    inst: &crate::card::CardInstance,
    objects: &std::collections::HashMap<ObjectId, crate::card::CardInstance>,
    battlefield: &std::collections::HashSet<ObjectId>,
    card_db: &crate::game::CardDatabase,
) -> bool {
    // Check that the source is still valid for WhileSourceOnBattlefield effects
    if effect.duration == Duration::WhileSourceOnBattlefield
        && !battlefield.contains(&effect.source_id)
    {
        return false;
    }

    match &effect.affected {
        AffectedObjects::OtherCreaturesWithSubtypeControlledBySource(_) => {
            // Control and type eligibility are checked after earlier layers run.
            obj_id != effect.source_id && battlefield.contains(&obj_id)
                && battlefield.contains(&effect.source_id)
        }
        AffectedObjects::Source => obj_id == effect.source_id,
        AffectedObjects::Specific(id) => obj_id == *id,
        AffectedObjects::AllCreatures => {
            // We need to check if this object is a creature.
            // At this point we check the base type — layer 4 type changes
            // could make something a creature, but for simplicity we use
            // the current known types. Full correctness requires a
            // dependency-aware approach (CR 613.8), deferred for now.
            is_creature_on_battlefield(obj_id, objects, battlefield, card_db)
        }
        AffectedObjects::CreaturesControlledBy(player) => {
            inst.controller == *player
                && is_creature_on_battlefield(obj_id, objects, battlefield, card_db)
        }
        AffectedObjects::OtherCreatures => {
            obj_id != effect.source_id
                && is_creature_on_battlefield(obj_id, objects, battlefield, card_db)
        }
        AffectedObjects::OtherCreaturesControlledBy(player) => {
            obj_id != effect.source_id
                && inst.controller == *player
                && is_creature_on_battlefield(obj_id, objects, battlefield, card_db)
        }
        AffectedObjects::OtherNonHumanCreaturesControlledBy(player) => {
            obj_id != effect.source_id
                && inst.controller == *player
                && is_creature_on_battlefield(obj_id, objects, battlefield, card_db)
                && !card_db
                    .get(inst.card_def_id)
                    .map(|def| def.subtypes.iter().any(|s| s.0 == "Human"))
                    .unwrap_or(false)
        }
        AffectedObjects::OtherCreaturesWithSubtypeControlledBy(subtype_name, player) => {
            obj_id != effect.source_id
                && inst.controller == *player
                && is_creature_on_battlefield(obj_id, objects, battlefield, card_db)
                && card_db
                    .get(inst.card_def_id)
                    .map(|def| def.subtypes.iter().any(|s| s.0 == *subtype_name))
                    .unwrap_or(false)
        }
        AffectedObjects::AllPermanents => battlefield.contains(&obj_id),
        AffectedObjects::PermanentsControlledBy(player) => {
            inst.controller == *player && battlefield.contains(&obj_id)
        }
        AffectedObjects::AttachedTo => {
            // The effect applies to whatever the source is attached to
            objects
                .get(&effect.source_id)
                .and_then(|src| src.attached_to)
                .map(|attached_id| obj_id == attached_id)
                .unwrap_or(false)
        }
    }
}

/// Check if an object is a creature on the battlefield.
/// Uses the base card type from the card definition — does not account for
/// type-changing effects (would need full dependency resolution per CR 613.8).
fn is_creature_on_battlefield(
    obj_id: ObjectId,
    objects: &std::collections::HashMap<ObjectId, crate::card::CardInstance>,
    battlefield: &std::collections::HashSet<ObjectId>,
    card_db: &crate::game::CardDatabase,
) -> bool {
    if !battlefield.contains(&obj_id) {
        return false;
    }
    match objects.get(&obj_id) {
        Some(inst) => card_db
            .get(inst.card_def_id)
            .map_or(false, |d| d.card_types.contains(&CardType::Creature)),
        None => false,
    }
}

/// A static ability on a card definition that generates continuous effects
/// when the permanent is on the battlefield.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum StaticAbility {
    /// Anthem: "Other creatures you control get +N/+N"
    Anthem {
        power: i32,
        toughness: i32,
        affected: AffectedObjects,
    },
    /// Grant a keyword to affected objects: "Creatures you control have flying"
    GrantKeyword {
        keyword: KeywordAbility,
        affected: AffectedObjects,
    },
    /// Set P/T of affected objects: "Creatures are 1/1" (e.g., Humility)
    SetPowerToughness {
        power: i32,
        toughness: i32,
        affected: AffectedObjects,
    },
    /// Remove all abilities from affected objects (e.g., Humility)
    RemoveAllAbilities {
        affected: AffectedObjects,
    },
    /// Change the color of affected objects
    SetColors {
        colors: Vec<Color>,
        affected: AffectedObjects,
    },
    /// Add a type to affected objects (e.g., Opalescence makes enchantments creatures)
    AddType {
        card_type: CardType,
        affected: AffectedObjects,
    },
    /// Whenever the controller taps a nonland permanent for mana, add one
    /// additional mana of any type that permanent produced.
    /// (e.g., Kinnan, Bonder Prodigy)
    ManaFromNonlandBonus,
    /// Whenever the controller taps a Swamp for mana, add an additional {B}.
    /// (e.g., Nirkana Revenant, Crypt Ghast)
    ManaFromSwampBonus,
    /// "You may play an additional land on each of your turns"
    /// (e.g., Exploration, Dryad of the Ilysian Grove, Azusa)
    ExtraLandDrops {
        count: u32,
    },
    /// "You may play lands from your graveyard"
    /// (e.g., Crucible of Worlds, Conduit of Worlds)
    PlayLandsFromGraveyard,
    /// "Each land you control is every basic land type in addition to its other types"
    /// (e.g., Prismatic Omen, Dryad of the Ilysian Grove)
    LandsAreAllBasicTypes,
    /// "Each land is a Forest in addition to its other land types"
    /// (e.g., Yavimaya, Cradle of Growth)
    AllLandsAreForests,
    /// "Creatures with power greater than the number of cards in your hand can't attack"
    /// (e.g., Ensnaring Bridge)
    EnsnaringBridge,
    /// While this card is in the graveyard and you control an Island, creatures you
    /// control have flying. (Wonder)
    /// Checked in refresh_continuous_effects from graveyard, not via to_continuous_effects.
    WonderInGraveyard,
    /// Replaces draws: instead of drawing, reveal cards until you find a land (or nonland).
    /// Put that card in hand, rest on bottom. (Abundance)
    /// Checked directly in draw_cards.
    AbundanceReplacement,
    /// Doubles draws when hand is empty: if you would draw with no cards in hand,
    /// draw two instead. (Phial of Galadriel)
    /// Checked directly in draw_cards.
    PhialDrawDoubler,
    /// Replaces draws: exile the top two cards instead of drawing one.
    /// You may play those cards this turn. (Renfield / Eruth)
    /// Checked directly in draw_cards — simplified as drawing 2 cards.
    RenfieldDrawReplacement,
    /// Grants each land you control "{T}: Mill a card." (Six)
    /// Checked directly in legal_actions.
    GrantLandsTapMill,
    /// You may play lands from exile that were exiled by this source. (Six)
    /// Checked directly in legal_actions.
    PlayLandsFromExileBySource,
}

impl StaticAbility {
    /// Convert this static ability into continuous effects generated
    /// by a specific permanent on the battlefield.
    pub fn to_continuous_effects(
        &self,
        source_id: ObjectId,
        controller: PlayerIndex,
        timestamp: u32,
    ) -> Vec<ContinuousEffect> {
        match self {
            StaticAbility::Anthem {
                power,
                toughness,
                affected,
            } => vec![ContinuousEffect {
                source_id,
                controller,
                timestamp,
                duration: Duration::WhileSourceOnBattlefield,
                affected: affected.clone(),
                modification: LayerModification::ModifyPT(*power, *toughness),
            }],
            StaticAbility::GrantKeyword { keyword, affected } => vec![ContinuousEffect {
                source_id,
                controller,
                timestamp,
                duration: Duration::WhileSourceOnBattlefield,
                affected: affected.clone(),
                modification: LayerModification::AddKeyword(*keyword),
            }],
            StaticAbility::SetPowerToughness {
                power,
                toughness,
                affected,
            } => vec![ContinuousEffect {
                source_id,
                controller,
                timestamp,
                duration: Duration::WhileSourceOnBattlefield,
                affected: affected.clone(),
                modification: LayerModification::SetPT(*power, *toughness),
            }],
            StaticAbility::RemoveAllAbilities { affected } => vec![ContinuousEffect {
                source_id,
                controller,
                timestamp,
                duration: Duration::WhileSourceOnBattlefield,
                affected: affected.clone(),
                modification: LayerModification::RemoveAllAbilities,
            }],
            StaticAbility::SetColors { colors, affected } => vec![ContinuousEffect {
                source_id,
                controller,
                timestamp,
                duration: Duration::WhileSourceOnBattlefield,
                affected: affected.clone(),
                modification: LayerModification::SetColors(colors.clone()),
            }],
            StaticAbility::AddType {
                card_type,
                affected,
            } => vec![ContinuousEffect {
                source_id,
                controller,
                timestamp,
                duration: Duration::WhileSourceOnBattlefield,
                affected: affected.clone(),
                modification: LayerModification::AddType(*card_type),
            }],
            // ManaFromNonlandBonus doesn't generate a continuous effect —
            // it's checked directly during mana ability activation in
            // rules::apply_action (ActivateManaAbility handler).
            StaticAbility::ManaFromNonlandBonus => vec![],
            StaticAbility::ManaFromSwampBonus => vec![],
            // These are checked directly in game logic, not via continuous effects:
            StaticAbility::ExtraLandDrops { .. } => vec![],
            StaticAbility::PlayLandsFromGraveyard => vec![],
            StaticAbility::LandsAreAllBasicTypes => vec![],
            StaticAbility::AllLandsAreForests => vec![],
            StaticAbility::EnsnaringBridge => vec![],
            // These are checked directly in specific game logic:
            StaticAbility::WonderInGraveyard => vec![],
            StaticAbility::AbundanceReplacement => vec![],
            StaticAbility::PhialDrawDoubler => vec![],
            StaticAbility::RenfieldDrawReplacement => vec![],
            StaticAbility::GrantLandsTapMill => vec![],
            StaticAbility::PlayLandsFromExileBySource => vec![],
        }
    }
}

/// Generate continuous effects from all permanents with static abilities
/// on the battlefield. This is called to refresh the effects list when
/// the battlefield changes.
pub fn generate_static_effects(
    battlefield: &[ObjectId],
    objects: &std::collections::HashMap<ObjectId, crate::card::CardInstance>,
    card_db: &crate::game::CardDatabase,
    next_timestamp: &mut u32,
) -> Vec<ContinuousEffect> {
    let mut effects = Vec::new();

    for &obj_id in battlefield {
        let inst = match objects.get(&obj_id) {
            Some(i) => i,
            None => continue,
        };
        let def = match card_db.get(inst.card_def_id) {
            Some(d) => d,
            None => continue,
        };

        for sa in &def.static_abilities {
            let generated = sa.to_continuous_effects(obj_id, inst.controller, *next_timestamp);
            *next_timestamp += 1;
            effects.extend(generated);
        }
    }

    effects
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::card::{CardDef, CardInstance, CardType, KeywordAbility, Subtype};
    use crate::game::CardDatabase;
    use crate::mana::ManaCost;
    use std::collections::{HashMap, HashSet};

    fn make_creature_def(id: u64, name: &str, power: i32, toughness: i32) -> CardDef {
        CardDef {
            id,
            name: name.into(),
            mana_cost: Some(ManaCost::new(1, 0, 0, 0, 0, 0)),
            card_types: vec![CardType::Creature],
            subtypes: vec![Subtype("Test".into())],
            power: Some(power),
            toughness: Some(toughness),
            ..Default::default()
        }
    }

    #[test]
    fn test_no_effects_returns_base_stats() {
        let mut db = CardDatabase::new();
        db.insert(make_creature_def(1, "Bear", 2, 2));

        let mut objects = HashMap::new();
        objects.insert(10, CardInstance::new(10, 1, 0));

        let battlefield: HashSet<ObjectId> = [10].into_iter().collect();
        let effects = vec![];

        let chars = compute_characteristics(10, &effects, &objects, &battlefield, &db).unwrap();
        assert_eq!(chars.power, 2);
        assert_eq!(chars.toughness, 2);
        assert!(chars.keywords.is_empty());
    }

    #[test]
    fn test_anthem_effect_modifies_pt() {
        let mut db = CardDatabase::new();
        db.insert(make_creature_def(1, "Bear", 2, 2));
        db.insert(make_creature_def(2, "Anthem Source", 0, 1));

        let mut objects = HashMap::new();
        objects.insert(10, CardInstance::new(10, 1, 0)); // Bear
        objects.insert(20, CardInstance::new(20, 2, 0)); // Anthem source

        let battlefield: HashSet<ObjectId> = [10, 20].into_iter().collect();

        let effects = vec![ContinuousEffect {
            source_id: 20,
            controller: 0,
            timestamp: 1,
            duration: Duration::WhileSourceOnBattlefield,
            affected: AffectedObjects::AllCreatures,
            modification: LayerModification::ModifyPT(1, 1),
        }];

        let chars = compute_characteristics(10, &effects, &objects, &battlefield, &db).unwrap();
        assert_eq!(chars.power, 3); // 2 + 1
        assert_eq!(chars.toughness, 3); // 2 + 1
    }

    #[test]
    fn test_multiple_anthems_stack() {
        let mut db = CardDatabase::new();
        db.insert(make_creature_def(1, "Bear", 2, 2));
        db.insert(make_creature_def(2, "Anthem1", 0, 1));
        db.insert(make_creature_def(3, "Anthem2", 0, 1));

        let mut objects = HashMap::new();
        objects.insert(10, CardInstance::new(10, 1, 0));
        objects.insert(20, CardInstance::new(20, 2, 0));
        objects.insert(30, CardInstance::new(30, 3, 0));

        let battlefield: HashSet<ObjectId> = [10, 20, 30].into_iter().collect();

        let effects = vec![
            ContinuousEffect {
                source_id: 20,
                controller: 0,
                timestamp: 1,
                duration: Duration::WhileSourceOnBattlefield,
                affected: AffectedObjects::AllCreatures,
                modification: LayerModification::ModifyPT(1, 1),
            },
            ContinuousEffect {
                source_id: 30,
                controller: 0,
                timestamp: 2,
                duration: Duration::WhileSourceOnBattlefield,
                affected: AffectedObjects::AllCreatures,
                modification: LayerModification::ModifyPT(1, 1),
            },
        ];

        let chars = compute_characteristics(10, &effects, &objects, &battlefield, &db).unwrap();
        assert_eq!(chars.power, 4); // 2 + 1 + 1
        assert_eq!(chars.toughness, 4);
    }

    #[test]
    fn test_humility_sets_pt_and_removes_abilities() {
        let mut db = CardDatabase::new();
        let mut bear_def = make_creature_def(1, "Bear", 2, 2);
        bear_def.keywords = vec![KeywordAbility::Flying];
        db.insert(bear_def);
        // Humility is an enchantment, not a creature, but we still need a def for it
        let mut humility_def = make_creature_def(99, "Humility", 0, 0);
        humility_def.card_types = vec![CardType::Enchantment];
        db.insert(humility_def);

        let mut objects = HashMap::new();
        objects.insert(10, CardInstance::new(10, 1, 0));
        objects.insert(99, CardInstance::new(99, 99, 0));

        let battlefield: HashSet<ObjectId> = [10, 99].into_iter().collect();

        // Humility: all creatures lose all abilities and are 1/1
        let effects = vec![
            ContinuousEffect {
                source_id: 99,
                controller: 0,
                timestamp: 1,
                duration: Duration::WhileSourceOnBattlefield,
                affected: AffectedObjects::AllCreatures,
                modification: LayerModification::RemoveAllAbilities,
            },
            ContinuousEffect {
                source_id: 99,
                controller: 0,
                timestamp: 1,
                duration: Duration::WhileSourceOnBattlefield,
                affected: AffectedObjects::AllCreatures,
                modification: LayerModification::SetPT(1, 1),
            },
        ];

        let chars = compute_characteristics(10, &effects, &objects, &battlefield, &db).unwrap();
        assert_eq!(chars.power, 1);
        assert_eq!(chars.toughness, 1);
        assert!(chars.keywords.is_empty()); // Lost flying
        assert!(chars.abilities_removed);
    }

    #[test]
    fn test_keyword_grant() {
        let mut db = CardDatabase::new();
        db.insert(make_creature_def(1, "Bear", 2, 2));
        let mut enchantment = make_creature_def(99, "Levitation", 0, 0);
        enchantment.card_types = vec![CardType::Enchantment];
        db.insert(enchantment);

        let mut objects = HashMap::new();
        objects.insert(10, CardInstance::new(10, 1, 0));
        objects.insert(99, CardInstance::new(99, 99, 0));

        let battlefield: HashSet<ObjectId> = [10, 99].into_iter().collect();

        let effects = vec![ContinuousEffect {
            source_id: 99,
            controller: 0,
            timestamp: 1,
            duration: Duration::WhileSourceOnBattlefield,
            affected: AffectedObjects::AllCreatures,
            modification: LayerModification::AddKeyword(KeywordAbility::Flying),
        }];

        let chars = compute_characteristics(10, &effects, &objects, &battlefield, &db).unwrap();
        assert!(chars.keywords.contains(&KeywordAbility::Flying));
    }

    #[test]
    fn test_counters_applied_in_layer_7d() {
        let mut db = CardDatabase::new();
        db.insert(make_creature_def(1, "Bear", 2, 2));

        let mut objects = HashMap::new();
        let mut bear = CardInstance::new(10, 1, 0);
        bear.plus_counters = 2;
        objects.insert(10, bear);

        let battlefield: HashSet<ObjectId> = [10].into_iter().collect();
        let effects = vec![];

        let chars = compute_characteristics(10, &effects, &objects, &battlefield, &db).unwrap();
        assert_eq!(chars.power, 4); // 2 + 2 counters
        assert_eq!(chars.toughness, 4);
    }

    #[test]
    fn test_anthem_plus_counters() {
        let mut db = CardDatabase::new();
        db.insert(make_creature_def(1, "Bear", 2, 2));
        let mut enchantment = make_creature_def(99, "Anthem", 0, 0);
        enchantment.card_types = vec![CardType::Enchantment];
        db.insert(enchantment);

        let mut objects = HashMap::new();
        let mut bear = CardInstance::new(10, 1, 0);
        bear.plus_counters = 1;
        objects.insert(10, bear);
        objects.insert(99, CardInstance::new(99, 99, 0));

        let battlefield: HashSet<ObjectId> = [10, 99].into_iter().collect();

        let effects = vec![ContinuousEffect {
            source_id: 99,
            controller: 0,
            timestamp: 1,
            duration: Duration::WhileSourceOnBattlefield,
            affected: AffectedObjects::AllCreatures,
            modification: LayerModification::ModifyPT(1, 1),
        }];

        let chars = compute_characteristics(10, &effects, &objects, &battlefield, &db).unwrap();
        // Base 2/2 + anthem +1/+1 (layer 7c) + 1 counter (layer 7d) = 4/4
        assert_eq!(chars.power, 4);
        assert_eq!(chars.toughness, 4);
    }

    /// Verify CR 613 layer 7d/7e interaction: +1/+1 counters are applied
    /// in layer 7d *before* the SwitchPT effect in layer 7e. A 2/4 creature
    /// with one +1/+1 counter becomes 3/5, then SwitchPT swaps to 5/3.
    #[test]
    fn test_counters_with_switch_pt() {
        let mut db = CardDatabase::new();
        // Asymmetric P/T so the swap is observable
        db.insert(make_creature_def(1, "Wall", 2, 4));

        let mut objects = HashMap::new();
        let mut wall = CardInstance::new(10, 1, 0);
        wall.plus_counters = 1; // one +1/+1 counter
        objects.insert(10, wall);

        let battlefield: HashSet<ObjectId> = [10].into_iter().collect();

        // A SwitchPT effect (e.g., Inside Out)
        let effects = vec![ContinuousEffect {
            source_id: 99,
            controller: 0,
            timestamp: 1,
            duration: Duration::UntilEndOfTurn,
            affected: AffectedObjects::Specific(10),
            modification: LayerModification::SwitchPT,
        }];

        let chars = compute_characteristics(10, &effects, &objects, &battlefield, &db).unwrap();
        // Base 2/4 + counter → 3/5 (layer 7d applied before 7e), then swap → 5/3
        assert_eq!(chars.power, 5);
        assert_eq!(chars.toughness, 3);
    }

    /// Verify counters + anthem + SwitchPT interaction. A 1/3 creature with
    /// +1/+1 anthem and one +1/+1 counter: base 1/3 → anthem 2/4 (7c) →
    /// counter 3/5 (7d) → swap 5/3 (7e).
    #[test]
    fn test_anthem_counters_switch_pt() {
        let mut db = CardDatabase::new();
        db.insert(make_creature_def(1, "Wall", 1, 3));
        let mut ench = make_creature_def(99, "Anthem", 0, 0);
        ench.card_types = vec![CardType::Enchantment];
        db.insert(ench);

        let mut objects = HashMap::new();
        let mut wall = CardInstance::new(10, 1, 0);
        wall.plus_counters = 1;
        objects.insert(10, wall);
        objects.insert(99, CardInstance::new(99, 99, 0));

        let battlefield: HashSet<ObjectId> = [10, 99].into_iter().collect();

        let effects = vec![
            ContinuousEffect {
                source_id: 99,
                controller: 0,
                timestamp: 1,
                duration: Duration::WhileSourceOnBattlefield,
                affected: AffectedObjects::AllCreatures,
                modification: LayerModification::ModifyPT(1, 1),
            },
            ContinuousEffect {
                source_id: 99,
                controller: 0,
                timestamp: 2,
                duration: Duration::UntilEndOfTurn,
                affected: AffectedObjects::Specific(10),
                modification: LayerModification::SwitchPT,
            },
        ];

        let chars = compute_characteristics(10, &effects, &objects, &battlefield, &db).unwrap();
        // Base 1/3 + anthem +1/+1 = 2/4 (7c) + counter +1/+1 = 3/5 (7d) → swap = 5/3 (7e)
        assert_eq!(chars.power, 5);
        assert_eq!(chars.toughness, 3);
    }

    #[test]
    fn test_other_creatures_excludes_source() {
        let mut db = CardDatabase::new();
        db.insert(make_creature_def(1, "Bear", 2, 2));
        db.insert(make_creature_def(2, "Anthem Lord", 1, 1));

        let mut objects = HashMap::new();
        objects.insert(10, CardInstance::new(10, 1, 0)); // Bear
        objects.insert(20, CardInstance::new(20, 2, 0)); // Lord

        let battlefield: HashSet<ObjectId> = [10, 20].into_iter().collect();

        // "Other creatures you control get +1/+1"
        let effects = vec![ContinuousEffect {
            source_id: 20,
            controller: 0,
            timestamp: 1,
            duration: Duration::WhileSourceOnBattlefield,
            affected: AffectedObjects::OtherCreatures,
            modification: LayerModification::ModifyPT(1, 1),
        }];

        // Bear should be buffed
        let bear_chars =
            compute_characteristics(10, &effects, &objects, &battlefield, &db).unwrap();
        assert_eq!(bear_chars.power, 3);

        // Lord should NOT be buffed (it's the source)
        let lord_chars =
            compute_characteristics(20, &effects, &objects, &battlefield, &db).unwrap();
        assert_eq!(lord_chars.power, 1);
    }

    #[test]
    fn test_timestamp_ordering_within_layer() {
        let mut db = CardDatabase::new();
        db.insert(make_creature_def(1, "Bear", 2, 2));
        let mut ench1 = make_creature_def(98, "Ench1", 0, 0);
        ench1.card_types = vec![CardType::Enchantment];
        db.insert(ench1);
        let mut ench2 = make_creature_def(99, "Ench2", 0, 0);
        ench2.card_types = vec![CardType::Enchantment];
        db.insert(ench2);

        let mut objects = HashMap::new();
        objects.insert(10, CardInstance::new(10, 1, 0));
        objects.insert(98, CardInstance::new(98, 98, 0));
        objects.insert(99, CardInstance::new(99, 99, 0));

        let battlefield: HashSet<ObjectId> = [10, 98, 99].into_iter().collect();

        // Two SetPT effects: later timestamp wins
        let effects = vec![
            ContinuousEffect {
                source_id: 99,
                controller: 0,
                timestamp: 1,
                duration: Duration::WhileSourceOnBattlefield,
                affected: AffectedObjects::AllCreatures,
                modification: LayerModification::SetPT(5, 5),
            },
            ContinuousEffect {
                source_id: 98,
                controller: 0,
                timestamp: 2,
                duration: Duration::WhileSourceOnBattlefield,
                affected: AffectedObjects::AllCreatures,
                modification: LayerModification::SetPT(1, 1),
            },
        ];

        let chars = compute_characteristics(10, &effects, &objects, &battlefield, &db).unwrap();
        // Second SetPT (timestamp 2) overwrites first
        assert_eq!(chars.power, 1);
        assert_eq!(chars.toughness, 1);
    }

    #[test]
    fn test_eot_effects_only_last_until_cleanup() {
        let mut db = CardDatabase::new();
        db.insert(make_creature_def(1, "Bear", 2, 2));

        let mut objects = HashMap::new();
        objects.insert(10, CardInstance::new(10, 1, 0));

        let battlefield: HashSet<ObjectId> = [10].into_iter().collect();

        // UntilEndOfTurn effect (like Giant Growth)
        let effects = vec![ContinuousEffect {
            source_id: 99,
            controller: 0,
            timestamp: 1,
            duration: Duration::UntilEndOfTurn,
            affected: AffectedObjects::Specific(10),
            modification: LayerModification::ModifyPT(3, 3),
        }];

        let chars = compute_characteristics(10, &effects, &objects, &battlefield, &db).unwrap();
        assert_eq!(chars.power, 5);
        assert_eq!(chars.toughness, 5);
    }

    #[test]
    fn test_static_ability_to_continuous_effects() {
        let sa = StaticAbility::Anthem {
            power: 1,
            toughness: 1,
            affected: AffectedObjects::OtherCreaturesControlledBy(0),
        };

        let effects = sa.to_continuous_effects(20, 0, 5);
        assert_eq!(effects.len(), 1);
        assert_eq!(effects[0].source_id, 20);
        assert_eq!(effects[0].timestamp, 5);
        assert_eq!(
            effects[0].modification,
            LayerModification::ModifyPT(1, 1)
        );
    }

    #[test]
    fn test_layer_modification_layer_order() {
        // Verify that layer ordering is correct
        assert!(LayerModification::CopyOf(0).layer() < LayerModification::ChangeController(0).layer());
        assert!(LayerModification::ChangeController(0).layer() < LayerModification::AddType(CardType::Creature).layer());
        assert!(LayerModification::AddType(CardType::Creature).layer() < LayerModification::AddColor(Color::White).layer());
        assert!(LayerModification::AddColor(Color::White).layer() < LayerModification::AddKeyword(KeywordAbility::Flying).layer());
        assert!(LayerModification::AddKeyword(KeywordAbility::Flying).layer() < LayerModification::SetBasePT(0, 0).layer());
        assert!(LayerModification::SetBasePT(0, 0).layer() < LayerModification::SetPT(0, 0).layer());
        assert!(LayerModification::SetPT(0, 0).layer() < LayerModification::ModifyPT(0, 0).layer());
        assert!(LayerModification::ModifyPT(0, 0).layer() < LayerModification::SwitchPT.layer());
    }
}
